Updated maestro dependencies
appcircleio/appcircle-workflow-components pull request #386
Opened 2024-04-24 16:31 UTC by ftmzhrsckldr

2024-05-01 08:56 UTC, boztopuz requested changes
@ftmzhrsckldr I think there is a mistake the versioning. We should discuss, please ping me on Slack to discuss this point before start to fix.

2024-05-01 08:56 UTC, boztopuz commented on appcircle_android_flutter_maestro_cloud_upload/1.0.1/component.yaml
After separate the component, you should have continue the last version. For example appcircle_maestro has 1.0.2 version. When you separate this component according to platforms, you should continue appcircle_flutter_maestro 1.0.3

The related conversation is https://appcircleteam.slack.com/archives/C02MNC1REJF/p1712225726720549?thread_ts=1712225615.505719&cid=C02MNC1REJF

2024-05-01 08:56 UTC, boztopuz commented on appcircle_android_maestro_cloud_upload/1.0.1/component.yaml
After separate the component, you should have continue the last version. For example appcircle_maestro has 1.0.2 version. When you separate this component according to platforms, you should continue appcircle_flutter_maestro 1.0.3

The related conversation is https://appcircleteam.slack.com/archives/C02MNC1REJF/p1712225726720549?thread_ts=1712225615.505719&cid=C02MNC1REJF

2024-05-01 08:56 UTC, boztopuz commented on appcircle_ios_flutter_maestro_cloud_upload/1.0.1/component.yaml
After separate the component, you should have continue the last version. For example appcircle_maestro has 1.0.2 version. When you separate this component according to platforms, you should continue appcircle_flutter_maestro 1.0.3

The related conversation is https://appcircleteam.slack.com/archives/C02MNC1REJF/p1712225726720549?thread_ts=1712225615.505719&cid=C02MNC1REJF

2024-05-01 18:15 UTC, ftmzhrsckldr commented on appcircle_android_flutter_maestro_cloud_upload/1.0.1/component.yaml
@boztopuz In the Slack link you added for reference, the topic was:
There was skipping in some component versions of which I was a reviewer. That is, like adding 1.0.2 after 1.0.0. And this was causing an error. We fixed this.

But in this case: the original version of Maestro was 1.0.0 and we used 1.0.1 for the Workflow Editor update, but since it was done incorrectly, I updated 1.0.1 again.

@csonuryilmaz Even though we made 1.0.1 wrong, should we have made the new version 1.0.2?

2024-05-02 16:27 UTC, ftmzhrsckldr commented on appcircle_android_flutter_maestro_cloud_upload/1.0.1/component.yaml
I consulted Onur and he said that a new version should be added. So like you said I added 1.0.2

2024-05-16 13:54 UTC, csonuryilmaz approved these changes

2024-05-16 13:55 UTC, merged