Updated doc links
appcircleio/appcircle-workflow-components pull request #390
Opened 2024-04-26 05:59 UTC by ftmzhrsckldr

2024-05-15 17:36 UTC, boztopuz requested changes

2024-05-15 17:36 UTC, boztopuz commented on appcircle_audit_permission_changes/1.0.2/component.yaml
> +docsUrl: https://docs.appcircle.io/workflows/ios-specific-workflow-steps/auidit-permission-change
```suggestion
https://docs.appcircle.io/workflows/ios-specific-workflow-steps/audit-permission-change
```

2024-05-15 17:36 UTC, boztopuz commented on appcircle_audit_permission_changes/1.0.2/component.yaml
> +docsUrl: https://docs.appcircle.io/workflows/ios-specific-workflow-steps/auidit-permission-change
Link is broken, because the file name has changed.

2024-05-16 09:00 UTC, csonuryilmaz approved these changes

2024-05-16 09:01 UTC, merged