Fixed Testinium requirement
appcircleio/appcircle-workflow-components pull request #395
Opened 2024-05-03 16:10 UTC by ftmzhrsckldr

2024-05-15 18:00 UTC, boztopuz requested changes

2024-05-15 18:00 UTC, boztopuz commented on appcircle_android_flutter_testinium/1.0.3/component.yaml
> +docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/#testinium
```suggestion
docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/testinium
```

2024-05-15 18:00 UTC, boztopuz commented on appcircle_android_flutter_testinium/1.0.4/component.yaml
> +docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/#testinium
```suggestion
docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/testinium
```

2024-05-15 18:00 UTC, boztopuz commented on appcircle_android_testinium/1.0.3/component.yaml
> +docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/#testinium
```suggestion
docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/testinium
```

2024-05-15 18:00 UTC, boztopuz commented on appcircle_android_testinium/1.0.4/component.yaml
> +docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/#testinium
```suggestion
docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/testinium
```

2024-05-15 18:00 UTC, boztopuz commented on appcircle_ios_flutter_testinium/1.0.3/component.yaml
> +docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/#testinium
```suggestion
docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/testinium
```

2024-05-15 18:00 UTC, boztopuz commented on appcircle_ios_flutter_testinium/1.0.4/component.yaml
> +docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/#testinium
```suggestion
docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/testinium
```

2024-05-15 18:00 UTC, boztopuz commented on appcircle_ios_testinium/1.0.3/component.yaml
> +docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/#testinium
```suggestion
docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/testinium
```

2024-05-15 18:00 UTC, boztopuz commented on appcircle_ios_testinium/1.0.4/component.yaml
> +docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/#testinium
```suggestion
docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/testinium
```

2024-05-15 18:00 UTC, boztopuz commented on appcircle_testinium/1.0.4/component.yaml
> +docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/#testinium
```suggestion
docsUrl: https://docs.appcircle.io/workflows/common-workflow-steps/testinium
```

2024-05-16 10:36 UTC, boztopuz approved these changes

2024-05-16 15:11 UTC, csonuryilmaz approved these changes

2024-05-16 15:13 UTC, merged